print()
x = float (input("Enter Number: "))
y = float (input ("Enter Number: "))
n = int (input ("Enter Decimal Places To Be Rounded Off To: "))
print()
print(f"+ {round(x, n)}")
print(f"+ {round(y, n)}")
print()